version: '3'
services:
  influxdb:
    image: influxdb:latest
    ports:
      - '86:8086'
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD:-admin}
  chronograf:
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - ./chronograf-data:/var/lib/chronograf
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=${INFLUXDB_URL:-influxdb}
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME:-admin}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD:-admin}
  grafana:
    image: grafana/grafana:latest
    ports:
      - '3001:3000'
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
volumes:
  influxdb-data:
  chronograf-data:
  grafana-data: