version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_db}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    ports:
      - "6033:3306"
    volumes:
      - './mysql-data:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PHPmyAdmin
    links:
      - mysql
    environment:
      PMA_HOST: ${PMA_HOST:-mysql}
      PMA_PORT: ${PMA_PORT:-3306}
      PMA_ARBITRARY: ${PMA_ARBITRARY:-1}
    restart: always
    ports:
      - 81:80
volumes:
  mysql-data: